### ISSUE TITLE
[Question] Why does this thing take so long to run?

### ISSUE THREAD

**Issue by ghost** [aneeshdurg/bash-raytracer#1]
When rendering a 64x64 image on Github Actions, this takes about 6 minutes to run.<br>Also when rendering a 512x512 image, it takes more than 6 hours, which is ridiculous.<br>Is it because of the sluggish operation of `bash` or something else?

**Comment by aneeshdurg** [comment]
It's not very optimized. `bash` is slow, but I think we can get some performance back by having the math functions store the result in a variable instead of echoing the result. Also, this is single threaded/single process. I'm sure parallelization would improve performance greatly.

I'd love to optimize this further, but that's pretty dependent when/if I have free time. If you're interesting in this, please feel free to submit a PR!

**Comment by ghost** [comment]
When I run this program, all cores max out at 100%. Doesn’t it mean that it’s multi threaded?(I don’t know stuff like this so sorry if I sound stupid)

**Comment by aneeshdurg** [comment]
Whoa that's very interesting. I wonder if bash is smarter than I thought. I'll try to do some real performance analysis this weekend to really understand what is slow instead of guessing

**Comment by aneeshdurg** [comment]
Oh it is multithreaded. Forgot I implemented that :joy:

**Comment by ghost** [comment]
So I guess the slow operation of this program is caused by bash. Maybe using zsh could speed it up a bit?

**Comment by aneeshdurg** [comment]
Possibly, but I think there's more that can be done in bash. To start with, I "inlined" addition and subtraction avoiding the need to output it as a string and parse it again which saved 10s when running with 8 processes:

```
# With inling
379.37user 94.31system 1:14.72elapsed 633%CPU (0avgtext+0avgdata 3980maxresident)k
0inputs+784outputs (0major+138801530minor)pagefaults 0swaps

# Without (current main branch)
427.32user 109.61system 1:25.39elapsed 628%CPU (0avgtext+0avgdata 3988maxresident)k
0inputs+416outputs (0major+159397630minor)pagefaults 0swaps
```
I find it interesting that nearly 25% of the time is spent in `system` though. Definitely want to dig deeper there, I assumed that this program would make almost 0 system calls aside from the initial spawning of processes.

**Comment by aneeshdurg** [comment]
Right now, as implemented, I think zsh wouldn't be significantly faster, unless arrays were implemented very differently in zsh.

**Comment by ghost** [comment]
Sounds very interesting, but what do you mean by 25% of the time is spent
on system calls?(I don’t know what those are precisely)
Also what is inlining calculations? Could you explain that to me please?

**Comment by ghost** [comment]
Could you commit the inlined script in the main branch? My [raytracer](https://github.com/7k5x/raytracer/) repo's Github workflow takes really long that it sometimes fails.

**Comment by aneeshdurg** [comment]
#2 probably helps with performance a lot. Huge thanks to @akinomyoga for working on it!
